[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
check_untyped_defs = true
disallow_incomplete_defs = true

[tool.black]
target-version = ["py310"]
line-length = 110
